### PR TITLE
css-canvas-medical - Logan Lee

### PR DESCRIPTION
**Pull request by loganlee-lth**
Screen Shot 2023-05-22 at 7 58 41 AM

### CODE REVIEW

**Comment by loganlee-lth** [comment]
Screen Shot 2023-05-22 at 9 57 56 AM

**Review by shawnkost — CHANGES_REQUESTED** [review]
Nice job Logan! Just one thing here that needs some fixing

1. The image should be aligned with the canvas logo. So the image should start where the canvas logo also begins

**Comment by loganlee-lth** [comment]
Screen Shot 2023-05-22 at 4 42 28 PM

**Review by shawnkost — CHANGES_REQUESTED** [review]
Seems like your fix also screwed up the other side! So the image needs to be aligned with the start of the canvas logo (which it now is), but it also needs to end where the button ends in the navbar. So it starts and ends at the exact same spot as everything in the navbar deos

**Comment by loganlee-lth** [comment]
Screen Shot 2023-05-23 at 1 54 44 PM

Sorry about the careless mistake!

**Review by shawnkost — APPROVED** [review]
👍🏻

**Pull request merged**
